name=DCMotorDriver_dff
version=1.0.0
author=David Chirme Sisa <davidcs.ee.10@gmail.com>
maintainer=David Chirme Sisa <davidcs.ee.10@gmail.com>
sentence=A library for controlling DC motors using motor drivers like the L298N.
paragraph=The DCMotorDriver library provides methods for motor initialization, direction control, speed control, and stopping the motor. It is designed to work with motor drivers such as the L298N and can be extended to other drivers.
category=Device Control
url=https://github.com/bulb-light/DCMotorDriver_dff
architectures=*
